### PR TITLE
fixbug issue #39

### PR DESCRIPTION
**Pull request by zj793039327**
#39

### CODE REVIEW

**Comment by hollingsworthd** [comment]
Hi, thanks for submitting this. Code looks good and didn't find any regressions. Before I merge, can you sign the contributor's license agreement? https://github.com/MachinePublishers/jBrowserDriver/blob/master/CLA-individual.txt ... you can do it electronically and add it to this pull request.

**Comment by zj793039327** [comment]
ok, i am going to sign

**Comment by hollingsworthd** [comment]
I incorporated your approach to fix the problem without directly copying. No need to sign CLA. Will be part of v0.9.2 release today/tomorrow. Thank you!

**Comment by zj793039327** [comment]
^_^ thank you

**Pull request closed without merging**
